name: inr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.3
  - numpy
  - pandas
  - pip
  - pip:
    - accelerate
    - requests
    - matplotlib
    - seaborn
    - tqdm
    - ipykernel
    - torch
    - torchvision
    - opencv-python
    - scikit-learn
    - scikit-image
    - scikit-video
    - scipy
    - wandb
    - configargparse
    - nibabel
    - ipyniivue
    - pysurfer
    - nilearn
    