sweep:
  enabled: true
  configuration:
    method: "grid"
    metric:
      goal: "minimize"
      name: "loss"
    parameters:
      nonlin:
        values: ["siren"]
      matter:
        values: ["hansen_full_pca", "hansen_full", "hansen_recommended"]
      gene_order:
        values: ["se"]
      lr:
        values: [1e-4]
      hidden_layers:
        values: [12]
      hidden_features:
        values: [512]
      total_steps:
        values: [100000]
      encoding_dim:
        values: [11]
      donor:
        values: ["9861", "10021"]
      schedule_free:
        values: [false]
  project: "hansen_experiments"
