sweep:
  enabled: true
  configuration:
    method: "grid"
    metric:
      goal: "minimize"
      name: "loss"
    parameters:
      nonlin:
        values: ["siren"]
      matter:
        values: ["hansen_recommended", "hansen_full"]
      gene_order:
        values: ["se"]
      lr:
        values: [5e-5]
      hidden_layers:
        values: [12]
      hidden_features:
        values: [512]
      total_steps:
        values: [100000]
      encoding_dim:
        values: [11]
      donor:
        values: ["9861", "10021"]
      schedule_free:
        values: [true]
  project: "hansen_experiments_sf"
